### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by tubb-lab** [avolkov1/keras_experiments#9]
Hi avolkov1
I get a problem when i run the mnist_tfrecord_mgpu.py, it is as follows:

Traceback (most recent call last):
  File "examples/mnist/mnist_tfrecord_mgpu.py", line 266, in <module>
    main()
  File "examples/mnist/mnist_tfrecord_mgpu.py", line 224, in main
    train_model.fit(epochs=epochs,batch_size=128)
  File "build/bdist.linux-x86_64/egg/keras/engine/training.py", line 1358, in fit
  File "build/bdist.linux-x86_64/egg/keras/engine/training.py", line 1245, in _standardize_user_data
  File "build/bdist.linux-x86_64/egg/keras/engine/training.py", line 597, in _standardize_weights
AttributeError: 'NoneType' object has no attribute 'shape'

the version of keras is '2.06',   Can you give me some pointers on how to fix this problem? Thanks !

**Comment by avolkov1** [comment]
@taozhiiq I updated the mnist_tfrecord_mgpu.py example. The initial version worked with Keras 2.0.6 and I was using a mixin to implement `.fit_tfrecord`, but it had bugs (refer to issue #6). Pull the latest code from this repo. The updated example is here:
[https://github.com/avolkov1/keras_experiments/blob/master/examples/mnist/mnist_tfrecord_mgpu.py](https://github.com/avolkov1/keras_experiments/blob/master/examples/mnist/mnist_tfrecord_mgpu.py)

The updated example requires latest Keras version 2.0.8. I think it will work with 2.0.7, but I have not tested it. The new features in Keras to simplify usage of a TF pipeline (tfrecord or queues or whatever) were introduced in [2.0.7](https://github.com/fchollet/keras/releases/tag/2.0.7). Please upgrade Keras. I use virtualenv for that so usually I upgrade like so:
```
pip install --upgrade keras --no-deps
```
That will upgrade to the latest Keras without changing or upgrading anything else.

**Comment by avolkov1** [comment]
@taozhiiq Have you had a chance to test with Keras 2.0.8? Let me know if there are still issues for mnist_tfrecord_mgpu.py example, otherwise please close this issue. Thanks.

**Comment by tubb-lab** [comment]
Thanks  very much for you answer, I have test it with the keras 2.08, and It works well.
